name: "TEST: Run pytest using tox"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 1'
jobs:
  test-older-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the dependencies
        run: uv sync --all-extras --dev
      - name: Test with pytest
        run: |
          uv run tox -e 'py-2.6,py-2.x'
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the dependencies
        run: uv sync --all-extras --dev
      - name: Test with pytest
        run: |
          uv run tox -e 'py-2.x'
